name: Lint

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**/*.cs'
      - '**/*.xaml'
      - '**/*.cshtml'
      - '**/*.csproj'
      - '**/*.sln'
      - '**/Directory.Build.props'
      - '**/.editorconfig'
      - .github/workflows/linter-dotnet.yml

jobs:
  main:
    name: 'Lint: .NET'
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Checkout ${{ github.event.repository.name }} repository
        uses: actions/checkout@v2

      - name: Check file
        id: check
        shell: pwsh
        run: Write-Output "::set-output name=run::$(Test-Path *.sln)"

      - name: Setup .NET
        if: steps.check.outputs.run == 'True'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100

      - name: .NET restore
        if: success()
        run: dotnet restore

      - name: Install dotnet format
        if: success()
        run: dotnet tool install -g dotnet-format --add-source https://dotnet.myget.org/F/format/api/v3/index.json

      - name: Lint .NET code
        if: success()
        run: dotnet format --check --fix-style info --fix-analyzers info --verbosity diagnostic