name: Lint

on:
  pull_request:
    types: [ opened, synchronize ]
    paths:
      - '**/*.cs'
      - '**/*.xaml'
      - '**/*.cshtml'
      - '**/*.csproj'
      - '**/*.sln'
      - '**/Directory.Build.props'
      - '**/.editorconfig'
      - .github/workflows/linter-dotnet.yml

jobs:
  main:
    name: 'Lint: .NET'
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
      - name: Check file
        id: check
        shell: pwsh
        run: Write-Output "::set-output name=run::$(Test-Path *.sln)"

      - name: Checkout ${{ github.event.repository.name }} repository
        if: steps.check.outputs.run == 'True'
        uses: actions/checkout@v2

      - name: Setup .NET
        if: steps.check.outputs.run == 'True'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100-rtm.20515.8

      - name: Cache nuget packages
        if: steps.check.outputs.run == 'True'
        uses: actions/cache@v2
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: nuget-

      - name: .NET restore
        if: steps.check.outputs.run == 'True'
        run: dotnet restore --locked-mode

      - name: Install dotnet format
        if: steps.check.outputs.run == 'True'
        run: dotnet tool install -g dotnet-format --add-source https://dotnet.myget.org/F/format/api/v3/index.json

      - name: Lint .NET code
        if: steps.check.outputs.run == 'True'
        run: dotnet format --check --fix-style info --fix-analyzers info --verbosity diagnostic